accounting/urls.py
from django.urls import path
from . import views, models

app_name = 'accounting'
urlpatterns = [
    path('', views.home_view, name='home'),
    #Borrar despues solo servira de prueba
    #path('prueba/', views.prueba_view, name='prueba'),
    #path('cuentas/<int:id>/', views.cuentas_view, name='cuentas'),
    #Borrar
    path('login/', views.login_view, name='login'),
    path('logout/', views.cerrarSesion, name='logout'),
    path('catalogo/', views.catalogo_view, name='catalogo'),
    path('controldecostos/', views.controlCostos_view, name='controlCostos'),
    path('transacciones/', views.transacciones_view, name='transacciones'),
    path('cuentas/<int:id>/', views.cuentas_view, name='cuentas'),
    #ENDPOINTS HECHOS POR CARLOS RAUDA
    path('transacciones/<int:year>/<int:month>/', views.obtenerNumeroTransaccion_view, name='obtenerNumeroTransaccion'),
    path('registrartransacciones/', views.registrarTransaccion_view, name='registrarTransaccion'),
    path('registrarOtraTabla/', views.registrarEnBalanceDeComprobacion_view, name='registrarEnBalanceDeComprobacion'),
    #ENDPOINTS HECHOS POR CARLOS RAUDA
    #Aqui van las rutas de las vistas de estados financieros, y las vistas que van dentro de esta.
    #-------------------------------------------------------------------------------------------------------------
    path('estadosfinancieros/', views.estadosFinancieros_view, name='estadosFinancieros'),
    path('balancedecomprobacion/', views.balanceDeComprobacion_view, name='balanceDeComprobacion'),
    path('estadoderesultados/', views.estadoDeResultados_view, name='estadoDeResultados'),
    path('estadodecapital/', views.estadoDeCapital_view, name='estadoDeCapital'),
    path('balancegeneral/', views.balanceGeneral_view, name='balanceGeneral'),
    #-------------------------------------------------------------------------------------------------------------
    path('libromayor/', views.libroMayor_view, name='libroMayor'),
    path('cierrecontable/', views.cierreContable_view, name='cierreContable'),
    path('balancecomprobacion/<int:year>/<int:month>/', views.balance_de_comprobacion_data, name='balanceDeComprobacionData'),
    path('libromayorget/<int:year>/<int:month>/', views.libro_mayor_data, name='libroMayorData'),
    path('estadoresultados/<int:year>/<int:month>/', views.estado_de_resultados_data, name='estadoDeResultadosData'),
    path('guardar_estado_resultados/', views.guardar_estado_resultados_view, name='guardarEstadoResultados'),
    path('estadodecapitaldata/<int:year>/<int:month>/', views.estado_de_capital_data, name='estadoDeCapitalData'),

    path('balancecomprobacion/', views.balance_de_comprobacion_data, name='balanceDeComprobacionData'),
    
    ##Control Costos,  
    path('agregarempleado/', views.agregar_empleado, name='agregarEmpleado'), 
    path('eliminar_empleado/<int:codigoEmpleado>/', views.eliminar_empleado, name='eliminarEmpleado'),
    path('costosmenu/', views.costosMenu_view, name='costosMenu'),
    path('costodesoftware/', views.costosSoftware_view, name='costoSoftware'),
    path('obtenerempleados/<int:departamento_id>', views.obtener_empleados, name='obtenerEmpleados'),
    path('proyecto/', views.proyecto_data, name='proyecto'),
    path('proyectoget/', views.proyecto_get, name='proyectoGet'),
]

accounting_software/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounting.urls')),
    #Borrar despues solo servira de prueba
    path('prueba/', include('accounting.urls')),
    path('cuentas/<int:id>/', include('accounting.urls')),
    #Borrar
    path('login/', include('accounting.urls')),
    path('logout/', include('accounting.urls')),
    path('catalogo/', include('accounting.urls')),
    path('controldecostos/', include('accounting.urls')),
    path('transacciones/', include('accounting.urls')),
    #ENDPOINTS HECHOS POR CARLOS RAUDA
    path('cuentas/<int:id>/', include('accounting.urls')),
    path('transacciones/<int:year>/<int:month>/', include('accounting.urls')),
    #ENDPOINTS HECHOS POR CARLOS RAUDA
    path('registrartransacciones/', include('accounting.urls')),
    path('estadosfinancieros/', include('accounting.urls')),
    path('balancedecomprobacion/', include('accounting.urls')),
    path('libromayor/', include('accounting.urls')),
    path('cierrecontable/', include('accounting.urls')),
    #Path que añadio Benitez
    path('estadoderesultados/', include('accounting.urls')),
    path('estadodecapital/', include('accounting.urls')),
    path('balancegeneral/', include('accounting.urls')),
    path('balancecomprobacion/<int:year>/<int:month>/', include('accounting.urls')),
    path('libromayorget/<int:year>/<int:month>/', include('accounting.urls')),

    path('balancecomprobacion/', include('accounting.urls')),
    path('agregarempleado/', include('accounting.urls')),
    path('controlcostos/', include('accounting.urls')),
    path('eliminar_empleado/<int:codigoEmpleado>/', include('accounting.urls')),
    path('costosmenu/', include('accounting.urls')),
    path('costodesoftware/', include('accounting.urls')),
    path('obtenerempleados/<int:departamento_id>', include('accounting.urls')),
    path('proyecto/', include('accounting.urls')),
    path('proyectoget/', include('accounting.urls')),
]

# Servir archivos estáticos en desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0] if settings.STATICFILES_DIRS else None)

accounting/views.py
# importaciones necesarias para trabajar con las vistas de la aplicacion accounting 
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
#from .models import //Aqui van los modelos a importar # importamos el modelo Usuario de la aplicacion accounting 
from django.contrib.auth.decorators import login_required 
from .models import CuentasMayor, CuentasDetalle, Transaccion, BalanceDeComprobacion, EstadoDeResultados, Empleado, Departamento, Proyecto
from django.views.decorators.csrf import csrf_exempt
import json
from django.db.models import Sum, Q
from datetime import datetime
# Create your views here.
# Create your views here.

""" #Modelo de la vista para Pruebas
def prueba_view(request):
    catalogos = Catalogo.objects.all()
    return render(request, 'transacciones.html', {'catalogos': catalogos})
#Borrar """

""" def cuentas_view(request, id):
    try:
        # Obtén el objeto Catalogo específico usando el `id`
        catalogo = Catalogo.objects.get(codigo=id)
        catalogo_data = {
            "codigo": catalogo.codigo,
            "cuenta": catalogo.cuenta
        }
        return JsonResponse(catalogo_data)
    except Catalogo.DoesNotExist:
        return JsonResponse({"error": "Catalogo no encontrado"}, status=404)
#Borrar """

@login_required
def home_view(request):
    return render(request, 'home.html')


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            return render(request, 'login.html', {'error': 'Usuario o contraseña incorrectos'})
    else:
        return render(request, 'login.html')

#Funcion para cerrar sesion
def cerrarSesion(request):
    logout(request)
    return redirect("/login")

@login_required
def catalogo_view(request):
    """ cuentasMayor = CuentasMayor.objects.all()
    cuentasDetalle = CuentasDetalle.objects.all() """
    cuentasMayor = CuentasMayor.objects.all()
    for cuenta in cuentasMayor:
        cuenta.cuentas_detalle = CuentasDetalle.objects.filter(codigoCuentaMayor_id=cuenta.codigoCuentaMayor)
    return render(request, 'catalogo.html', {'cuentas': cuentasMayor})

def controlCostos_view(request):
    empleados = Empleado.objects.all()
    empleados_data = [calcular_datos_empleado(empleado) for empleado in empleados]
    departamentos = Departamento.objects.all()
    print(departamentos)
    return render(request, 'controlCostos.html', {'empleados': empleados_data, 'departamentos': departamentos})

def transacciones_view(request):
    cuentasMayor = CuentasMayor.objects.all()
    for cuenta in cuentasMayor:
        cuenta.cuentas_detalle = CuentasDetalle.objects.filter(codigoCuentaMayor_id=cuenta.codigoCuentaMayor)
    return render(request,'transacciones.html', {'catalogos': cuentasMayor})

# SIRVE PARA RECUPERAR EL CATALOGO DE CUENTAS
def cuentas_view(request, id):
    try:
        """ catalogo_data = {
            "codigo": catalogo.codigo,
            "cuenta": catalogo.cuenta
        } """
        # Obtén el objeto Catalogo específico usando el `id`
        if(CuentasDetalle.objects.filter(codigoCuenta=id).exists()):
            cuentaDetalle = CuentasDetalle.objects.get(codigoCuenta=id)
            cuentaMayor = CuentasMayor.objects.get(codigoCuentaMayor=cuentaDetalle.codigoCuentaMayor_id)
            catalogo_data = {
                "codigo": cuentaMayor.codigoCuenta,
                "cuenta": cuentaMayor.nombreCuenta,
                "cuenta_detalle": {
                    "codigo": cuentaDetalle.codigoCuenta,
                    "cuenta": cuentaDetalle.nombreCuenta,
                }
            }
        else:
            cuentaMayor = CuentasMayor.objects.get(codigoCuenta=id)
            catalogo_data = {
                "codigo": cuentaMayor.codigoCuenta,
                "cuenta": cuentaMayor.nombreCuenta,
                "cuenta_detalle": {
                    "codigo": "",
                    "cuenta": "",
                }
            }
        return JsonResponse(catalogo_data)
    except CuentasMayor.DoesNotExist:
        return JsonResponse({"error": "Catalogo no encontrado"}, status=404)

# SIRVE PARA CALCULAR EL NUMERO DE PARTIDA
def obtenerNumeroTransaccion_view(request, year, month):
    if(Transaccion.objects.filter(fecha__year=year, fecha__month=month).exists()):
        transacciones = Transaccion.objects.filter(fecha__year=year, fecha__month=month)
        ultima_transaccion = transacciones.last()
        numero = {
            "numero": ultima_transaccion.numeroPartida + 1
        }
    else:
        numero = {
            "numero": 1
        }
        print(numero)
    return JsonResponse(numero)

# SIRVE PARA REGISTRAR UNA TRANSACCION
def registrarTransaccion_view(request):
    if request.method == 'POST':
        try:
            datos = json.loads(request.body)
            transaccion = Transaccion(
                numeroPartida=datos['numero_partida'],
                fecha=datos['fecha'],
                codigoCuenta=datos['codigo'],
                nombreCuenta=datos['cuenta'],
                Cargo=float(datos['cargo']),
                Abono=float(datos['abono'])
            )
            transaccion.save()
            return JsonResponse({"mensaje": "Datos recibidos correctamente"})
        except Exception as e:
            return JsonResponse({'success': False, 'message': str(e)})
    else:
        return JsonResponse({"error": "Método no permitido"}, status=405)

# SIRVE PARA REGISTRAR UNA TRANSACCION EN BALANCE DE COMPROBACION
@csrf_exempt
def registrarEnBalanceDeComprobacion_view(request):
    if request.method == 'POST':
        try:
            datos = json.loads(request.body)
            balance = BalanceDeComprobacion(
                numeroPartida=datos['numero_partida'],
                fecha=datos['fecha'],
                codigoCuenta=datos['codigo'],
                nombreCuenta=datos['cuenta'],
                Cargo=float(datos['cargo']),
                Abono=float(datos['abono'])
            )
            balance.save()
            return JsonResponse({"mensaje": "Datos registrados en Balance de Comprobacion correctamente"})
        except Exception as e:
            return JsonResponse({'success': False, 'message': str(e)})
    else:
        return JsonResponse({"error": "Método no permitido"}, status=405)

#Aqui va la vista de estados financieros, y las vistas que van dentro de esta.
#-------------------------------------------------------------------------------------------------------------
def estadosFinancieros_view(request):
    return render(request, 'estadosFinancieros.html')

#Las siguientes son las sub-templates de estados financieros

def balanceDeComprobacion_view(request):
    return render(request, 'balanceComprobacion.html')

def estadoDeResultados_view(request):
    return render(request, 'estadoResultados.html')

def estadoDeCapital_view(request):
    return render(request, 'estadoCapital.html')

def balanceGeneral_view(request):
    return render(request, 'balanceGeneral.html')
#-------------------------------------------------------------------------------------------------------------

def libroMayor_view(request):
    return render(request, 'libroMayor.html')

#Esta vista es la que faltaba en el menu.
def cierreContable_view(request):
    return render(request, 'cierreContable.html')

def costosMenu_view(request):
    return render(request, 'costosMenu.html')

def costosSoftware_view(request):
    departamentos = Departamento.objects.all()
    return render(request, 'costosSoftware.html', {'departamentos': departamentos})

def obtener_empleados(request, departamento_id):
    empleados = Empleado.objects.filter(codigoDepartamento_id=departamento_id)
    print(empleados)
    empleados_data = [calcular_datos_empleado(empleado) for empleado in empleados]
    print(empleados_data)
    return JsonResponse(empleados_data, safe=False)

#Aqui van los objetos de las tablas de las cuentas de mayor y detalle, se crean con el script crear_cuentas.py

#Pruebas

from django.db.models import Sum, Case, When, F

@login_required
def balance_de_comprobacion_data(request, year, month):
    transacciones = (
        BalanceDeComprobacion.objects
        .filter(fecha__year=year, fecha__month=month)
        .values("codigoCuenta", "nombreCuenta")
        .annotate(
            total_cargo=Sum("Cargo"),
            total_abono=Sum("Abono"),
            saldo=Case(
                When(total_abono__gt=F('total_cargo'), then=F('total_abono') - F('total_cargo')),
                default=F('total_cargo') - F('total_abono')
            )
        )
        .order_by("codigoCuenta")
    )

    data = list(transacciones)
    return JsonResponse(data, safe=False)

def libro_mayor_data(request, year, month):
    try:
        transacciones = (
            Transaccion.objects
            .filter(fecha__year=year, fecha__month=month)
            .values("codigoCuenta", "nombreCuenta", "fecha", "numeroPartida", "Cargo", "Abono")
            .order_by("codigoCuenta", "fecha")
        )
        data = list(transacciones)
        return JsonResponse(data, safe=False)
    except Exception as e:
        # Imprime el error en la consola y devuelve un JSON de error
        print("Error:", e)
        return JsonResponse({"error": "Error al procesar las transacciones"}, status=500)

@login_required
def estado_de_resultados_data(request, year, month):
    # Obtener todas las cuentas de ingresos (5xxx) y gastos (4xxx)
    cuentas = BalanceDeComprobacion.objects.filter(
        fecha__year=year, fecha__month=month
    ).filter(

accounting/templates/balanceComprobacion.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Balance Comprobación - Software Contable TAS</title>
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/estadosFinancieros.css' %}">
</head>
<body>
    {% include 'includes/navbar.html' %}
    
    <main class="libro-mayor-container">
            <div class="page-header">
                <h2 class="section-title">Balance Comprobación</h2>
                <a href="{% url 'accounting:estadosFinancieros' %}" class="btn-back">
                    <span>←</span> Regresar a Estados Financieros
                </a>
            </div>
            <div class="fecha-container">
                <div>
                    <label for="fecha">Fecha:</label>
                    <input type="month" id="fecha" name="fecha">
                </div>
            </div>
            <div class="table-container">
                <table class="libro-mayor-table">
                    <thead>
                        <tr>
                            <th>Código</th>
                            <th>Cuenta</th>
                            <th>Cargo</th>
                            <th>Abono</th>
                            <th>Saldo Deudor</th>
                            <th>Saldo Acreedor</th>
                        </tr>
                    </thead>
                    <tbody id="tabla-resultados">
                        <!-- Los datos se cargarán aquí -->
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="2"><strong>TOTALES:</strong></td>
                            <td id="total-cargo">$0.00</td>
                            <td id="total-abono">$0.00</td>
                            <td id="total-deudor">$0.00</td>
                            <td id="total-acreedor">$0.00</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
    </main>
    <script src="{% static 'js/balanceComprobacion.js' %}"></script>
</body>
</html>

accounting/templates/balanceGeneral.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Balance General - Software Contable TAS</title>
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/estadosFinancieros.css' %}">
</head>
<body>
    {% include 'includes/navbar.html' %}
    
    <main class="libro-mayor-container">
        <div class="page-header">
            <h2 class="section-title">Balance General</h2>
            <a href="{% url 'accounting:estadosFinancieros' %}" class="btn-back">
                <span>←</span> Regresar a Estados Financieros
            </a>
        </div>
        <div class="fecha-container">
            <div>
                <label for="fecha">Fecha:</label>
                <input type="month" id="fecha" name="fecha">
            </div>
        </div>
            <div class="table-container">
                <table class="libro-mayor-table">
                    <thead>
                        <tr>
                            <th>Código</th>
                            <th>Nombre de Cuenta</th>
                            <th>Saldo Deudor</th>
                            <th>Saldo Acreedor</th>
                        </tr>
                    </thead>
                    <tbody id="tabla-resultados">
                        <!-- Filas adicionales se llenarán dinámicamente -->
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="2"><strong>TOTALES:</strong></td>
                            <td id="total-cargo">$0.00</td>
                            <td id="total-abono">$0.00</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
    </main>
    
    <script src="{% static 'js/balanceGeneral.js' %}"></script>
</body>
</html>

accounting/templates/controlCostos.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Control de Costos - Software Contable TAS</title>
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/controlCostos.css' %}">
</head>

<body>
    {% include 'includes/navbar.html' %}
    
    <div class="control-costos-container">
        <div class="page-header">
            <h2 class="section-title">Control de Costos Semanales de Empleados</h2>
            <a href="{% url 'accounting:costosMenu' %}" class="btn-back">
                <span>←</span> Regresar al Menú de Costos
            </a>
        </div>

        <div class="table-container">
            <div class="contenedor-boton">
                <button class="one-btn" onclick="abrirModal()">Agregar Empleado</button>
            </div>
            <table class="control-costos-table">
                <thead>
                    <tr>
                        <th>Empleado</th>
                        <th>Puesto</th>
                        <th>Pago Diario</th>
                        <th>Costo Real</th>
                        <th>Septimo Día</th>
                        <th>Vacaciones</th>
                        <th>Aguinaldo</th>
                        <th>ISSS</th>
                        <th>AFP</th>
                        <th>INCAFF</th>
                        <th>Salario Total</th>
                        <th>Acción</th>
                    </tr>
                </thead>
                <tbody>
                    {% for empleado in empleados %}
                    <tr>
                        <td>{{ empleado.nombreEmpleado }}</td>
                        <td>{{ empleado.puestoEmpleado }}</td>
                        <td>${{ empleado.salarioDiarioEmpleado|floatformat:2 }}</td>
                        <td>${{ empleado.costo_real|floatformat:2 }}</td>
                        <td>${{ empleado.septimo_dia|floatformat:2 }}</td>
                        <td>${{ empleado.vacaciones|floatformat:2 }}</td>
                        <td>${{ empleado.aguinaldo|floatformat:2 }}</td>
                        <td>${{ empleado.isss|floatformat:2 }}</td>
                        <td>${{ empleado.afp|floatformat:2 }}</td>
                        <td>${{ empleado.incaff|floatformat:2 }}</td>
                        <td>${{ empleado.salario_total|floatformat:2 }}</td>
                        <td>
                            <button class="two-btn" value="{{empleado.codigoEmpleado}}"
                                onclick="eliminarEmpleado(this)">Eliminar</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    
    <!-- Modal de Registrar Empleado -->
    <div id="modalEmpleado" class="modal">
        <div class="modal-contenido">
            <h2>Registrar Empleado</h2>
            <form method="post">
                {% csrf_token %}
                <label for="nombreEmpleado">Nombre del empleado:</label>
                <input type="text" id="nombreEmpleado" placeholder="Nombre">

                <label for="puestoTrabajo">Puesto de trabajo:</label>
                <input type="text" id="puestoTrabajo" placeholder="Puesto">

                <label for="salario">Salario Diario:</label>
                <input type="text" id="salario" placeholder="Salario">

                <label for="dias">Días de Trabajo:</label>
                <input type="text" id="dias" placeholder="Días de Trabajo">

                <select name="departamentos" id="departamento" class="departamentos">
                    <option value="" selected disabled>Selecciona una opción</option>
                    {% for departamento in departamentos %}
                    <option value="{{ departamento.codigoDepartamento }}">{{ departamento.nombreDepartamento }}</option>
                    {% endfor %}
                </select>

                <div class="modal-botones">
                    <button type="button" onclick="cerrarModal()" class="btn-cancelar">Cerrar</button>
                    <button type="submit" class="btn-guardar">Guardar</button>
                </div>
            </form>
        </div>
    </div>

    <script src="{% static 'js/controlCostos.js' %}"></script>
</body>

</html>

accounting/templates/costosSoftware.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Costos de Software - Software Contable TAS</title>
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/costosSoftware.css' %}">
</head>

<body>
    {% include 'includes/navbar.html' %}
    
    <main class="container">
        <div class="page-header">
            <h2 class="section-title">Control de Costos de Software</h2>
            <a href="{% url 'accounting:costosMenu' %}" class="btn-back">
                <span>←</span> Regresar al Menú de Costos
            </a>
        </div>
        
        <button class="add-btn" onclick="openDepartmentsModal()">Seleccionar Departamentos</button>

        <div class="table-container">
            <table class="table">
                <thead>
                    <tr>
                        <th>Proyecto</th>
                        <th>Total</th>
                        <th>Unidades a Producir</th>
                        <th>Costo Unitario</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </main>

    <!-- Modal para seleccionar departamentos -->
    <div id="departmentsModal" class="modal">
        <div class="modal-content">
            <h2>Selecciona los Departamentos</h2>
            <div class="option checkbox-container">
                {% for departamento in departamentos %}
                <label class="checkbox-label">
                    <input type="checkbox" value="{{  departamento.codigoDepartamento }}"> 
                    {{ departamento.nombreDepartamento }}
                </label>
                {% endfor %}
            </div>            
            <div class="option">
                <label>Nombre del proyecto
                    <input type="text" id="proyectName" class="small-input">
                </label>
                <label>Costos indirectos de fabricación: 
                    <input type="number" id="indirectCost" class="small-input" min="0">
                </label>
                <label>Unidades a producir: 
                    <input type="number" id="unitsToProduce" class="small-input" min="1">
                </label>
            </div>
            <div class="option-btn">
                <button onclick="nextModal()">Siguiente</button>
                <button onclick="closeModal('departmentsModal')">Cancelar</button>
            </div>
        </div>
    </div>

    <!-- Modal para ingresar detalles del departamento seleccionado -->
    <div id="departmentDetailsModal" class="modal">
        <div class="modal-content">
            <h2>Detalles del Departamento</h2>
            <div class="option">
                <div id="empleado"></div>                
                <label>Costos de indirectos de fabricación del departamento en %: 
                    <input type="number" id="fabricationCost" class="small-input" min="0">
                </label>
            </div>
            <div class="option-btn">
                <button onclick="saveDepartmentDetails()">Guardar</button>
                <button onclick="closeModal('departmentDetailsModal')">Cancelar</button>
            </div>
        </div>
    </div>
    
    <script src="{% static 'js/costoSoftware.js' %}"></script>
</body>
</html>

accounting/templates/estadoCapital.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Estado de Capital - Software Contable TAS</title>
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/estadosFinancieros.css' %}">
</head>
<body>
    {% include 'includes/navbar.html' %}
    
    <main class="libro-mayor-container">
        <div class="page-header">
            <h2 class="section-title">Estado de Capital</h2>
            <a href="{% url 'accounting:estadosFinancieros' %}" class="btn-back">
                <span>←</span> Regresar a Estados Financieros
            </a>
        </div>
        <div class="fecha-container">
            <div>
                <label for="fecha">Fecha:</label>
                <input type="month" id="fecha" name="fecha">
            </div>
        </div>
        <div class="table-container">
            <table class="libro-mayor-table">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Nombre de Cuenta</th>
                        <th>Cargo</th>
                        <th>Abono</th>
                    </tr>
                </thead>
                <tbody id="estado-capital-body">
                    <!-- Filas adicionales se llenarán dinámicamente -->
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="2"><strong>TOTAL:</strong></td>
                        <td id="total-cargo">$0.00</td>
                        <td id="total-abono">$0.00</td>
                    </tr>
                    <tr>
                        <td colspan="3"><strong>Capital Actualizado:</strong></td>
                        <td id="capital">$0.00</td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </main>
    
    <script src="{% static 'js/estadoCapital.js' %}"></script>
</body>
</html>

accounting/templates/vistaDePrueba.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hola como estas</title>

    <h2>Prueba esta es una prueba</h2>
</head>
<body>
    
</body>
</html>